name: connection_notifier
description: A Flutter package that notifies when there is no internet connection, and provides simple tools to help track connection status.
version: 2.0.1+2
homepage: https://github.com/AmrAbdelmagid/connection_notifier
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  meta: ^1.15.0
  internet_connection_checker:
    git: https://github.com/presence-app/internet_connection_checker.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
